# Generated by Django 5.1 on 2024-09-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='daet',
            field=models.DateField(blank=True, null=True),
        ),
    ]
