# Generated by Django 5.1 on 2024-09-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_daet_task_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='payment',
            field=models.FloatField(default=0.0),
        ),
    ]
