# Generated by Django 5.1 on 2024-09-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_description_task_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='payment',
            field=models.TextField(blank=True),
        ),
    ]
