# Generated by Django 5.1 on 2024-09-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.TextField(blank=True),
        ),
    ]
