# Generated by Django 5.1 on 2024-09-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='budget_edit',
            field=models.TextField(blank=True),
        ),
    ]
